CLASS zbp_worklist DEFINITION public ABSTRACT FINAL
                   FOR BEHAVIOR OF ZI_AccHarmoAccounts.
  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zbp_worklist IMPLEMENTATION.
ENDCLASS.
