CLASS zbp_project DEFINITION public ABSTRACT FINAL
                  FOR BEHAVIOR OF ZI_AccHarmoProject.
  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zbp_project IMPLEMENTATION.
ENDCLASS.
